services:
  jupyterlab:
    image: jupyter/base-notebook:latest
    container_name: jupyterlab
    ports:
      - "888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=3719  # Set a secure token
      - NB_UID=1000       # Replace with your UID
      - NB_GID=1000       # Replace with your GID
    restart: unless-stopped
