project:
  type: website

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    
website:
  title: "Web Development tools"
  image: "bird.jpg"
  favicon: "bird.jpg"
  reader-mode: true
  back-to-top-navigation: true
  page-navigation: true
  twitter-card: true
  open-graph: true
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: overlay

  navbar:
    background: dark
    logo: "bird.jpg"
    logo-alt: "Quarto logo."
    collapse-below: lg
    title: false
    left:
      - text: "Blog"
        href: https://bthek1.github.io/benedicts_blog/
      - text: "AI"
        menu:
        - text: "Fast AI Setup"
          href: https://bthek1.github.io/FastAISetup/
        - text: " Fast AI course"
          href: https://bthek1.github.io/fastAIcourse/
          
      - text: "ML"
        menu:
        - text: "Machine Learning course"
          href: https://bthek1.github.io/ML/
          
      - text: "Timeseries"    
        menu:
        - text: "Time series course"
          href: https://bthek1.github.io/TimeSeriesML/
          
      - text: "Web Development"
        menu:
        - text: "Documentation"
          href: https://bthek1.github.io/webdevelopment_doc/
        - text: "React"
          href: https://bthek1.github.io/webdevelopment_doc/React/react.html
        - text: "Django"
          href: https://bthek1.github.io/webdevelopment_doc/django.html
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/quarto-dev/quarto-cli/issues/new/choose"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/quarto-dev/quarto-cli/issues/new/choose"
          - text: "FAQ"
            icon: "question-circle"
            href: "https://github.com/quarto-dev/quarto-cli/issues/new/choose"
          
    tools:
      - icon: github
        href: "https://github.com/bthek1/benedicts_blog.git"
        aria-label: Github
      - icon: linkedin
        href: "https://www.linkedin.com/in/benedict-thekkel/"
        aria-label: Linkedin


  page-footer:
    center:
      - text: "About"
        href: "index.ipynb"
      - text: "FAQ"
        href: "https://github.com/bthek1/benedicts_blog/wiki"    
      - text: "License"
        href: "https://bthek1.github.io/benedicts_blog/Index.html"
      - text: "Trademark"
        href: "index.ipynb"
        
        
    right:
      - icon: github
        href: "https://github.com/bthek1/benedicts_blog.git"
        aria-label: Github
      - icon: linkedin
        href: "https://www.linkedin.com/in/benedict-thekkel/"
        aria-label: Linkedin

  comments: 
    utterances:
      repo: quarto-dev/quarto-web
        
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]