services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "800:8000"   # Port for Portainer Agent (optional)
      - "9443:9443"   # Port for Portainer UI over HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # Access to Docker daemon
      - ./portainer_data:/data                        # Persistent Portainer data

volumes:
  portainer_data:
